// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM-M29KZ-UvimJ2rMoLN1-5uWOLkXS3ow',
    appId: '1:662617742303:web:30899165e0978fd247826a',
    messagingSenderId: '662617742303',
    projectId: 'veemadeforyou-a4946',
    authDomain: 'veemadeforyou-a4946.firebaseapp.com',
    storageBucket: 'veemadeforyou-a4946.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfQ4Cq59p81hU8cv1xkudjMve9LFRv8H4',
    appId: '1:662617742303:android:6527849958e3ee2247826a',
    messagingSenderId: '662617742303',
    projectId: 'veemadeforyou-a4946',
    storageBucket: 'veemadeforyou-a4946.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsO6-po9ymfpQaB6BwaGl_o2MflcprFgA',
    appId: '1:662617742303:ios:acf4723e57f06cc347826a',
    messagingSenderId: '662617742303',
    projectId: 'veemadeforyou-a4946',
    storageBucket: 'veemadeforyou-a4946.firebasestorage.app',
    iosBundleId: 'com.veemadeforyou.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsO6-po9ymfpQaB6BwaGl_o2MflcprFgA',
    appId: '1:662617742303:ios:20abc8b4b438bb6747826a',
    messagingSenderId: '662617742303',
    projectId: 'veemadeforyou-a4946',
    storageBucket: 'veemadeforyou-a4946.firebasestorage.app',
    iosBundleId: 'com.example.firstProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM-M29KZ-UvimJ2rMoLN1-5uWOLkXS3ow',
    appId: '1:662617742303:web:a5e3f714c999b77647826a',
    messagingSenderId: '662617742303',
    projectId: 'veemadeforyou-a4946',
    authDomain: 'veemadeforyou-a4946.firebaseapp.com',
    storageBucket: 'veemadeforyou-a4946.firebasestorage.app',
  );
}
